version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "20:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
      - dependency-name: org.springframework.boot:spring-boot-starter-parent
        versions:
          - ">= 3"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "daily"
      time: "20:00"
      timezone: "Asia/Shanghai"
